### ISSUE TITLE
have a default grass species in the table: orchardgrass

### ISSUE THREAD

**Issue by emchasen** [Grasslands-2/GrazeScape#110]

**Comment by cgrattonUW** [comment]
Are we switching these to "low productivity grass", medium, etc...

**Comment by emchasen** [comment]
Good call @cgrattonUW . Yes we should rename the grasses in the dropdown menu to something generic that encapsulates low, medium and high yielding grasses. I wonder what the best word choice is. We should also find a way to communicate to users what grasses might be included in each of these groupings - like a pop up info bubble or something.

**Comment by zhassler** [comment]
We need to change the language to low, med, and high yielding groups.  Use map tips to show which species are in each group.  
Default to low yield group when field is set up(blue grass) 

Timinothy is med
orchard grass is high
