### ISSUE TITLE
store model results so that they don't have to be re-run with each additional scenario

### ISSUE THREAD

**Issue by emchasen** [Grasslands-2/GrazeScape#113]

**Comment by mmbayles** [comment]
The app should already be saving past scenario runs in the database. Are you seeing something different @emchasen?

**Comment by emchasen** [comment]
@mmbayles I guess that isn't clear to me. If you close out of model results, the only way to view them again is to hit rerun models and it takes another moment. So perhaps I mean more that you should be able to open and close model results without having to hit 'rerun'. I also think I meant this note to point to the fact that someone may want to enter two scenarios at a time without having to run the models separately. Does that make sense?

**Comment by mmbayles** [comment]
Yep those are both good requests.
